name: Build & Test

on: push

jobs:
  os_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: jrl-umi3218/github-actions/install-dependencies@master
        with:
          compiler: clang
          ubuntu: |
            apt: libeigen3-dev
          macos: |
            brew: eigen
      - name: CMake
        run: cmake -S . -B build -DCMAKE_CXX_COMPILER=$(which clang++)
      - name: Build hyped
        run: cd build; make -j
      - name: Test
        run: cd build; ctest