on: [push]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.9.0
        with:
          clang-format-version: "13"
          style: "file"

  find-todos-fixme:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Run todo check
        run: | 
         if grep --exclude-dir={.git,.github} -rE "TODO|FIXME"; then
          exit 1
         else
          echo "All good"
         fi
